[tool.uv.workspace]
members = ["packages/bot"]

[dependency-groups]
dev = ["pytest-asyncio~=0.26.0", "pytest-cov~=6.0.0", "pytest~=8.3.5", "ruff~=0.9"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
